language: c
compiler:
  - gcc
  - clang
sudo: required

install:
  - sudo apt-get install python3

script:
  - mkdir build && cd build && cmake ../ && make && cd ..
  - chmod +x script/test.sh
  - ./script/test.sh